<%@ codepage=65001 %>

<!--#include virtual = "V5/Inc/Setup.asp"-->
<!--#include virtual = "V5/Inc/Initialize.asp"-->
<!--#include virtual = "V5/Inc/Db_Phra.asp"-->
<!--#include virtual = "V5/Inc/Db_Cust.asp"-->
<!--#include virtual = "V5/Inc/Db_Prog.asp"-->
<!--#include virtual = "V5/Inc/Db_Mods.asp"-->
<!--#include virtual = "V5/Inc/Certificate.asp"-->

<!--#include virtual = "V5/Inc/RTE.asp"-->
<!--#include file    = "RTE_Routines.asp"-->

<%  
	Dim vUrl, vProgId
  vProgId = Request("vProgId")
	'...get basics (need to refresh)
	sRTEsessionCore svMembNo, Clng(Request("vProgNo").Item), Request("vModsId").Item, Request("vProgId").Item
	'...get objectives (even expired ones)
	sRTEsessionObj2 svMembNo, RTE_ProgNo, RTE_ModsNo
%>

<html>

  <head>
    <title>RTE_ModsStat</title>
    <link href="/V5/Inc/Vubi2.css" type="text/css" rel="stylesheet">
    <script src="/V5/Inc/Functions.js"></script>
    <script src="/V5/Inc/jQuery.js"></script>
    <script>
		  // this saves the original click position so we can return it 
		  // should we need to generate a cert using the openWindow call 
		  // value is passed in parm3 to re-open this window at the original y postion 
		  // not the current y/mouseclick position which will be generated by the click
		  // on the certificate button.
		  var saveY = pageY;
    </script>
    <style>

      .modsStat th { width:30%; }
      .modsStat td { width:70%; }

    </style>


  </head>

  <body>

    <h2><!--[[-->Module Details<!--]]--></h2>

    <table class="modsStat">
      <tr>
        <td colspan="2">&nbsp;</td>
      </tr>
      <tr>
        <th><!--[[-->Module Id<!--]]-->:</th>
        <td><%=RTE_ModsId %>&nbsp;&nbsp;&nbsp; <%=RTE_ModsTitle %></td>
      </tr>
      <tr>
        <th><!--[[-->Module Status<!--]]-->:</th>
        <td><%=RTE_Status%> *</td>
      </tr>
      <% If RTE_TimeSpent > 0 Then%>
      <tr>
        <th><!--[[-->Time Spent in Module<!--]]-->:</th>
        <td><%=RTE_TimeSpent%>&nbsp;<!--[[-->minute<!--]]-->(s)</td>
      </tr>
      <% End If %>
      <tr>
        <th><!--[[-->Last Accessed<!--]]-->:</th>
        <td><%=fFormatDateTime(RTE_LastDate)%></td>
      </tr>
      <tr>
        <th colspan="2">&nbsp;</th>
      </tr>
    </table>
    
    
  <% If RTE_Attempts > 0 Then %> 

  <br><br><br>
  <h2><!--[[-->Assessment Details<!--]]--></h2>

    <table class="modsStat">
      <tr>
        <th>&nbsp;</th>
        <td colspan="2">&nbsp;</td>
        <td rowspan="4" style="width: 50%">

          <fieldset>
            <legend><!--[[-->History<!--]]--></legend>
            <table class="table">
              <%

                Dim aScores  : aScores  = Split(RTE_Scores,  "|")
                Dim aDates   : aDates   = Split(RTE_Dates,   "|")
                Dim aExpired : aExpired = Split(RTE_Expired, "|")
                Dim bExpired : bExpired = False

                For i = 0 To Ubound(aScores)
                  Response.Write "<tr><td nowrap>" & fFormatDateTime(aDates(i)) & "</td><td nowrap>" & f5 & aScores(i) & "%</td><td nowrap class='green'>" & f5 & fFormatDateTime(aExpired(i)) & "</span></td></tr>"                      
                  If IsDate(aExpired(i)) Then bExpired = True
                Next

                If bExpired Then Response.Write "<tr><td colspan='3' class='green'>Dates in green are when completed recurring assessments are/were eligible for retake.</td></tr>"

              %>
            </table>
          </fieldset>

        </td>
      </tr>


      <%  If RTE_BestScore > 0 Then %>

      <tr>
        <th><!--[[-->Last Score<!--]]-->:</th>
        <td>
          <%
  				  Response.Write RTE_BestScore
  				%>
        </td>
        <td>
  				<%  
  			    If RTE_Completed And RTE_ModsVuCert Then 
  		  		  vUrl = fCertificateUrl("", "", RTE_BestScore, RTE_CompletedDate, RTE_ModsId, RTE_ModsTitle, "", "", "", RTE_ProgId, "", "", "")
          %>
              <input onclick="openWindow('C', '<%=vUrl%>', saveY)" type="button" value="Certificate" name="B5" class="button070">
          <% 
      		  End If 
          %> 
        </td>
      </tr>
      <% End If  %>


      <%  If RTE_Failed Then %>
      <tr>
        <th><!--[[-->Assessment Status<!--]]-->:</th>
        <td>Failed</td>
        <td>&nbsp;</td>
      </tr>
      <%  End If  %>
      <tr>
        <th><!--[[-->Attempts Used<!--]]-->:</th>
        <td><%=RTE_NoAttempts & " of " & fRTE_MaxAttempts(vProgId)%></td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <th colspan="4">&nbsp;</th>
      </tr>
    </table>

  <% End If %>
    
  <br><br>


  <h2>*  <!--[[-->Status Legend<!--]]--></h2>

  <table class="modsStat">
    <tr>
      <th>&nbsp;</th>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <th><!--[[-->Not Started<!--]]-->:</th>
      <td><!--[[-->Module has not been accessed.<!--]]--></td>
    </tr>
    <tr>
      <th><!--[[-->Reviewed<!--]]-->:</th>
      <td><!--[[-->Module has been previously accessed and may be in progress or completed.<!--]]--></td>
    </tr>
    <tr>
      <th><!--[[-->Completed<!--]]-->:</th>
      <td><!--[[-->Note: some modules may not use or set this status.<!--]]--></td>
    </tr>
    <tr>
      <th><!--[[-->Failed<!--]]-->:</th>
      <td><!--[[-->An embedded assessment was not passed using the attempts available.<!--]]--></td>
    </tr>
    <tr>
      <th colspan="2">&nbsp;</th>
    </tr>
  </table>

  </body>

</html>
